sudo: false

language: c
 
addons:
  apt:
    packages:
    - luarocks
    - pandoc

install:
  - eval $(luarocks path --bin)
  - luarocks install --local luacheck
 
script: /home/travis/.luarocks/bin/luacheck . --no-color -quiet -only "011"
 
after_script:
  - curl -sO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
  - curl -s https://gist.githubusercontent.com/p3lim/d77edf45f2c6e29b6f2dc23140028a45/raw/8974b8b8856dc33d658402b2a88bf888da46c259/release.patch | git apply -v
  - bash release.sh

notifications:
  email:
    on_failure: always
    on_success: never

cache:
  apt: true
  directories:
    - $HOME/.luarocks

branches:
  only:
  - /^r\d+(-(alpha|beta))?(-\d+)?$/